#!/bin/bash

docker rm -f db

docker run -d --name="db" \
-p 127.0.0.1:5434:5432 \
-e POSTGRES_USER=odoo \
-e POSTGRES_PASSWORD=odoo \
-v /Users/danielb/odoo/pg/database:/var/lib/postgresql/data \
postgres:9.5
