version: '2'
services:
    db:
        # restart: always
        container_name: db
        image: postgres:9.5
        ports:
          - "5433:5432"
        environment:
          - PGDATA=/var/lib/postgresql/data/pgdata
          - POSTGRES_USER=odoo
          - POSTGRES_PASSWORD=odoo
        volumes:
          - db-data:/var/lib/postgresql/data/pgdata
    odoo:
        # restart: always
        container_name: odoo10
        image: hub.bmya.cl:5000/bmya-odoo11c:l02
        command: -- -c /etc/odoo/odoo.conf    
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - odoo-data:/var/lib/odoo
            - ./extra-addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - DB_PORT_5432_TCP_ADDR=db
            - DB_PORT_5432_TCP_PORT=5432
            - DB_ENV_POSTGRES_USER=odoo
            - DB_ENV_POSTGRES_PASSWORD=odoo
volumes:
    odoo-data:
    db-data:
